@startuml
actor User
control Router <<@angular>> #orange

entity LanguageGuard #lightgreen
entity TranslateService <<Plugin>> #orange

User -> Router: /

activate Router #orange

note over Router
  /
end note

Router -> LanguageGuard: canActivate()
activate LanguageGuard #lightgreen
LanguageGuard -> LanguageGuard:
note right
  get :lang from cookie, browser or use default
end note
LanguageGuard ->> Router: /:lang
deactivate LanguageGuard

note over Router
  /:lang
end note

Router -> LanguageGuard: canActivate(:lang)
activate LanguageGuard #lightgreen

LanguageGuard ->> TranslateService: setLanguage(:lang)
LanguageGuard --> Router: grant access
deactivate LanguageGuard

Router -> Router: redirect to /:lang/ICD

...resolve catalog route...

Router --> User: display
deactivate Router


@enduml
