@startuml
actor User
control Router <<@angular>> #orange
entity CatalogElementResolver as ElementResolver #lightgreen
entity CatalogElementCache as Cache #lightgrey
entity "ICDCatalog \n <<Placeholder for any Catalog>>" as ICD #lightgreen

participant DetailComponent #lightblue

== Navigate to CatalogHierarchy ==

User -> Router:
activate Router #orange

note over Router
    de/ICD/ICD10-GM-2016/icds/E20.0
end note

...resolve language and catalog...
Router -> ElementResolver: resolve(...)
activate ElementResolver #lightgrey

ElementResolver -> Cache: getElement('de', 'ICD10-GM-2016','icds', 'E20.0')
activate Cache #lightgreen
Cache -> ElementResolver: element:CatalogElement or Null

deactivate Cache #lightgreen

group element not in cache
    ElementResolver --> ICD: getElement('de','ICD10-GM-2016', 'icds', 'E20.0')
    activate ICD #lightgreen

    note over ICD
       get element from eonum API
    end note

    ICD --> ElementResolver: element: CatalogElement
    deactivate ICD


    ElementResolver -> Cache: save element
    activate Cache #lightgreen
    Cache --> ElementResolver
    deactivate Cache #lightgreen

    loop for all parent elements
        ElementResolver --> ICD: getElement(...)
        activate ICD #lightgreen

        note over ICD
           get element from eonum API
        end note

        ICD --> ElementResolver: element: CatalogElement
        deactivate ICD
        ElementResolver -> Cache: save element
        activate Cache #lightgreen
        Cache --> ElementResolver
        deactivate Cache #lightgreen

    end
end

ElementResolver --> Router: element:CatalogElement
deactivate ElementResolver

Router -> DetailComponent: element

activate DetailComponent #lightblue

DetailComponent --> Router
deactivate DetailComponent #lightblue

Router -> User: display
deactivate Router

@enduml
