@startuml
actor User
control Router <<@angular>> #orange

entity "ICDCatalog \n <<Placeholder for any Catalog>>" as ICD #lightgreen

entity CatalogSearchService as SearchService #lightgreen
participant SearchFormComponent #lightblue
participant SearchResultsComponent as ResultsComp #lightblue

== Load Page / Catalog Search (Without Hierarchy loading) ==

User -> SearchFormComponent: enter search-query: 'a query'

activate SearchFormComponent #lightblue

SearchFormComponent -> Router: navigate({query:'a query'}
deactivate SearchFormComponent #lightblue

activate Router #orange


Router ->> ResultsComp: {params:{'de', 'ICD', '2016' }, queryParams{query}}

activate ResultsComp  #lightblue

group search query in route params

    ResultsComp  -> SearchService: search('de', 'ICD', '2016', query)
    activate SearchService #lightgreen
    note over SearchService
    end note
    SearchService ->> ICD: search('de', '2016', query)



    activate ICD #lightgreen

    note over ICD
       Search in eonum API
       end note

    ICD --> SearchService: searchResults: CatalogElement[]
    deactivate ICD

    SearchService --> ResultsComp: searchResults:CatalogElement[]
    deactivate SearchService #lightgreen
    ResultsComp  -> ResultsComp : display results

end

ResultsComp  --> Router
deactivate ResultsComp

Router --> User: display
deactivate Router



@enduml
